### ISSUE TITLE
Nullpointerexception because "key" is null

### ISSUE THREAD

**Issue by AlphaOmega-IT** [ABravePanda/LootCrate#31]
Hey, trying to get to the next page of the items section. In the entire gui page are no items added. That causes a nullpointer exception, when trying to get to the next page. 

` Cannot invoke "lootcrate.objects.CrateKey.getItem()" because "key" is null
        at lootcrate.gui.items.GUIItem.<init>(GUIItem.java:66) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.menu.CrateKeyFrame.fillOptions(CrateKeyFrame.java:49) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.menu.CrateKeyFrame.generateFrame(CrateKeyFrame.java:38) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.menu.CrateKeyFrame.<init>(CrateKeyFrame.java:30) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.menu.CrateItemFrame.nextPage(CrateItemFrame.java:112) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.types.BasicFrame.onInventoryClickEvent(BasicFrame.java:238) ~[LootCrate-0.9.1.jar:?]`

**Comment by AlphaOmega-IT** [comment]
![nullpointer](https://user-images.githubusercontent.com/67145970/178160084-4e122f25-1bed-4457-8740-df461f261023.PNG)

Clicking on this without having any items, or anything added causes Nullpointerexception as well. 

`java.lang.NullPointerException: Cannot invoke "lootcrate.objects.CrateKey.getItem()" because "key" is null
        at lootcrate.gui.items.GUIItem.<init>(GUIItem.java:66) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.menu.CrateKeyFrame.fillOptions(CrateKeyFrame.java:49) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.menu.CrateKeyFrame.generateFrame(CrateKeyFrame.java:38) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.menu.CrateKeyFrame.<init>(CrateKeyFrame.java:30) ~[LootCrate-0.9.1.jar:?]
        at lootcrate.gui.frames.menu.CrateFrame.onGUIItemClick(CrateFrame.java:76) ~[LootCrate-0.9.1.jar:?]
`

**Comment by ABravePanda** [comment]
Thanks for the heads up, currently working on a GUI redesign right now so hopefully fixed soon
