### ISSUE TITLE
Error occurred while disabling LootCrate v0.9.1 (Is it up to date?) java.lang.NullPointerException: Cannot invoke "lootcrate.managers.Manager.disable()" because "m" is null

### ISSUE THREAD

**Issue by DENPOY** [ABravePanda/LootCrate#35]
[11:15:49 ERROR]: Error occurred while disabling LootCrate v0.9.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "lootcrate.managers.Manager.disable()" because "m" is null
        at lootcrate.LootCrate.toggleManagers(LootCrate.java:91) ~[?:?]
        at lootcrate.LootCrate.onDisable(LootCrate.java:78) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:906) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:763) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.close(MinecraftServer.java:862) ~[patched_1.16.5.jar:git-Paper-794]
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:162) ~[patched_1.16.5.jar:git-Paper-794]

**Comment by ABravePanda** [comment]
Known issue, to be fixed soon

**Comment by DENPOY** [comment]
YOU ANSWER YEAH!

can I get a link to the discord server of your plugins?

**Comment by TylBurxyz** [comment]
> YOU ANSWER YEAH!
> 
> can I get a link to the discord server of your plugins?

https://discord.gg/9Ct7H3x5
