### ISSUE TITLE
Could not pass event CrateViewEvent

### ISSUE THREAD

**Issue by CastedShadow** [ABravePanda/LootCrate#42]
**Minecraft Version:** `1.19.2`
**Paper Version:** `paper-1.19.2-142`
**LootCrate Version:** `LootCrate-0.10.0`
<hr>

Hello. I recently downloaded the mod and tested it out for a while. However, during testing, the "Left-click to view" action does not always trigger. Upon checking the console, I was met with this:

```java
[02:55:17 ERROR]: Could not pass event CrateViewEvent to LootCrate v0.10.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()" because "meta" is null
        at lootcrate.utils.ItemUtils.addRandomizer(ItemUtils.java:50) ~[LootCrate-0.10.0.jar:?]
        at lootcrate.managers.InventoryManager.addCrateEffects(InventoryManager.java:45) ~[LootCrate-0.10.0.jar:?]
        at lootcrate.gui.frames.CrateViewFrame.generateFrame(CrateViewFrame.java:38) ~[LootCrate-0.10.0.jar:?]
        at lootcrate.gui.frames.CrateViewFrame.<init>(CrateViewFrame.java:29) ~[LootCrate-0.10.0.jar:?]
        at lootcrate.events.listeners.custom.CrateViewListener.onView(CrateViewListener.java:20) ~[LootCrate-0.10.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor253.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-142]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at lootcrate.events.listeners.custom.CrateAccessListener.onAccess(CrateAccessListener.java:41) ~[LootCrate-0.10.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor251.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-142]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at lootcrate.events.listeners.LootCrateInteractListener.onPlayerInteractEvent(LootCrateInteractListener.java:58) ~[LootCrate-0.10.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor250.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-142]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:198) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1882) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1465) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

I have only created one LootCrate so far.

This is my `crates.yml` file:

```YAML
crates:
  '947':
    Id: 947
    Name: LLGacha
    Options:
      Knockback: 1.0
      Animation-Style: RANDOM_GLASS
      Display-Chances: true
      Open-Sound: UI_TOAST_CHALLENGE_COMPLETE
      Open-Message: '&fYou have opened &e{crate_name}&f.'
      Hologram-Enabled: true
      Hologram-Lines:
      - '{crate_name}'
      - '&8Right-Click&7 to Unlock'
      - '&8Left-Click&7 to View'
      Hologram-Offset-X: 0.5
      Hologram-Offset-Y: 1.8
      Hologram-Offset-Z: 0.5
    Key:
      Item:
        v: 3120
        type: PAPER
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#D1D0A3","text":"Daily
            LLGacha Ticket"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#4E598C","text":"Use
            on LLGacha crates!"}],"text":""}'
          enchants:
            OXYGEN: 1
            DURABILITY: 10
          ItemFlags:
          - HIDE_ENCHANTS
          PublicBukkitValues:
            lootcrate:lootcrate-key: 947i
      Glowing: true
    Items:
    - ==: lootcrate.objects.CrateItem
      ID: 93197
      Item:
        v: 3120
        type: FILLED_MAP
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"[1⭐]
            "},{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FFD3E8","text":"Miyuu
            Sakurada"},{"bold":false,"italic":false,"text":" - Uniform"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"No
            available episodes."}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}'
          - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Hold
            on... what is this even for?"}],"text":""}'
          - '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#DFFFD6","text":"Gift
            Item"}],"text":""}'
          map-id: 25
      Chance: 90.0
      MinAmount: 1
      MaxAmount: 1
      isDisplay: false
      Commands: []
    - ==: lootcrate.objects.CrateItem
      ID: 56611
      Item:
        v: 3120
        type: FILLED_MAP
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"[1⭐]
            "},{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FE6F01","text":"Rinku
            Aimoto"},{"bold":false,"italic":false,"text":" "},{"italic":false,"color":"white","text":"-
            Uniform"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"No
            available episodes."}],"text":""}'
          - '{"text":""}'
          - '{"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Hold
            on... what is this even for?"}],"text":""}'
          - '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#DFFFD6","text":"Gift
            Item"}],"text":""}'
          map-id: 26
      Chance: 90.0
      MinAmount: 1
      MaxAmount: 1
      isDisplay: false
      Commands: []
    - ==: lootcrate.objects.CrateItem
      ID: 32353
      Item:
        v: 3120
        type: MUSIC_DISC_BLOCKS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#E182AA","text":"Sakurada
            Resort Gift Shop Disc"}],"text":""}'
          lore:
          - '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FFB1E3","text":"Michiru
            Exercise No. 1"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#FFB1E3","text":"Michiru
            Kaibara"}],"text":""}'
          ItemFlags:
          - HIDE_ENCHANTS
          - HIDE_ATTRIBUTES
          - HIDE_UNBREAKABLE
          - HIDE_DESTROYS
          - HIDE_PLACED_ON
          - HIDE_POTION_EFFECTS
          - HIDE_DYE
          PublicBukkitValues:
            customdiscs:customdisc: Michiru_Exercise_No.1.mp3
      Chance: 2.0
      MinAmount: 1
      MaxAmount: 1
      isDisplay: false
      Commands: []
```

The only remedy is to reload the plugin. I hope it gets fixed!

**Comment by ABravePanda** [comment]
Thanks for reporting the bug. I think I know what the issue is. Will be patched in next update :)

**Comment by TylBurxyz** [comment]
> Think ours may be a different error, however. We are using custom items from another plugin, could that be causing the issue?
> 
> It seems we can set up all of the items (70) and most of them work fine but we lose about 10%-20% of them each time. This error is shown when trying to view the crate after adding them and you are not able to actually open the GUI to view them. After restarting the server, you can view them again but around 10%-20% of what was added will be gone.
> 
> https://pastebin.com/nM6A7JXR

Custom items from other plugins have not been the cause of any issues as of yet; if you are adding items from your inventory (instead of in config), it is recommended to add the items then immediately reload the plugin before moving anything in your inventory.  A known bug will cause some items to vanish otherwise.

Feel free to join the Discord Support server here: https://discord.gg/FMHPnCwbNX
