### ISSUE TITLE
crate config direct editing error

### ISSUE THREAD

**Issue by WolfLiSteel** [ABravePanda/LootCrate#47]
30.12 11:41:24 [Server] INFO Enabling LootCrate v0.10.2
30.12 11:41:25 [Server] ERROR Error occurred while enabling LootCrate v0.10.2 (Is it up to date?)
30.12 11:41:25 [Server] INFO java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of "lootcrate.objects.Crate.getName()" is null
30.12 11:41:25 [Server] INFO at lootcrate.managers.HologramManager.createHologram(HologramManager.java:44) ~[LootCrate-0.10.2.jar:?]
30.12 11:41:25 [Server] INFO at lootcrate.managers.HologramManager.reload(HologramManager.java:65) ~[LootCrate-0.10.2.jar:?]
30.12 11:41:25 [Server] INFO at lootcrate.managers.HologramManager.enable(HologramManager.java:72) ~[LootCrate-0.10.2.jar:?]
30.12 11:41:25 [Server] INFO at lootcrate.LootCrate.toggleManagers(LootCrate.java:94) ~[LootCrate-0.10.2.jar:?]
30.12 11:41:25 [Server] INFO at lootcrate.LootCrate.onEnable(LootCrate.java:70) ~[LootCrate-0.10.2.jar:?]
30.12 11:41:25 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
30.12 11:41:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
30.12 11:41:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
30.12 11:41:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
30.12 11:41:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
30.12 11:41:25 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
30.12 11:41:25 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
30.12 11:41:25 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
30.12 11:41:25 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
30.12 11:41:25 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
30.12 11:41:25 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
30.12 11:41:25 [Server] INFO Disabling LootCrate v0.10.2

**Comment by WolfLiSteel** [comment]
Just wanna say it got fixed after removing the colorcodes in names

**Comment by WolfLiSteel** [comment]
unable to put colorcodes on names. and name changing not responding

**Comment by WolfLiSteel** [comment]
mostly name changing problem
