### ISSUE TITLE
Getting this bug every few seconds

### ISSUE THREAD

**Issue by SaphiLC** [ABravePanda/LootCrate#9]
```
[13:42:42 ERROR]: Could not pass event PlayerInteractEvent to LootCrate v0.3.3
java.lang.NullPointerException: null
        at lootcrate.utils.ObjUtils.isKey(ObjUtils.java:77) ~[?:?]
        at lootcrate.events.listeners.LootCrateInteractEvent.onPlayerInteractEvent(LootCrateInteractEvent.java:55) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-584]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-584]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-584]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-584]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:531) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:498) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1698) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1381) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-584]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-584]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by ABravePanda** [comment]
Have seen this issue before, will look into it. Thank you for bringing it to my attention.

**Comment by ABravePanda** [comment]
There is a pending updated (0.3.4) to come soon, this should solve the issue. I will close this when the update is released. Should be released soon.

**Comment by Rudomeister** [comment]
I have this spam in console as well. Reproduced on naked testserver. It's player interactevent with fist only. It throws this exception when punching the ground even. Not sure if this has any impact on anything else, except you can see in console when players are using fist on something. Except that, thanks so much for keeping this plugin alive!

**Comment by ABravePanda** [comment]
Should be fixed with newest spigot release. If not fixed, please feel free to make a new issue for it. Thank you all for your help and patience! 

New release: https://www.spigotmc.org/resources/lootcrate-server-crate-plugin-1-16-x-server-must-have-free.87046/
